# k8s/kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80 # This is a list item, so it starts with '-'
    hostPort: 80
    listenAddress: "0.0.0.0"
    protocol: tcp
  - containerPort: 443 # This is another list item
    hostPort: 443
    listenAddress: "0.0.0.0"
    protocol: tcp
