# Deployment for finance-mcp
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: finance-mcp-deployment
      namespace: multi-agent-bot
      labels:
        app: finance-mcp
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: finance-mcp
      template:
        metadata:
          labels:
            app: finance-mcp
        spec:
          containers:
          - name: finance-mcp
            image: finance-mcp-server:latest 
            ports:
            - containerPort: 9000
            envFrom:
            - configMapRef:
                name: bot-config
            - secretRef:
                name: bot-secrets # For any finance-related API keys
            imagePullPolicy: Never
    
    
    