# Service for discord-mcp
    # k8s/services/discord-mcp-svc.yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: discord-mcp-svc # DNS name for the Discord MCP
      namespace: multi-agent-bot
    spec:
      selector:
        app: discord-mcp # Matches the 'app' label of your discord-mcp pods
      ports:
        - protocol: TCP
          port: 9000 # The port this Service listens on
          targetPort: 9000 # The port on the container
      type: ClusterIP
    