# Service for finance-mcp
    apiVersion: v1
    kind: Service
    metadata:
      name: finance-mcp-svc # DNS name for the Finance MCP
      namespace: multi-agent-bot
    spec:
      selector:
        app: finance-mcp # Matches the 'app' label of your finance-mcp pods
      ports:
        - protocol: TCP
          port: 9000 # The port this Service listens on
          targetPort: 9000 # The port on the container
      type: ClusterIP
    