# Service for web-mcp
    apiVersion: v1
    kind: Service
    metadata:
      name: web-mcp-svc # DNS name for the Web MCP
      namespace: multi-agent-bot
    spec:
      selector:
        app: web-mcp # Matches the 'app' label of your web-mcp pods
      ports:
        - protocol: TCP
          port: 9000 # The port this Service listens on
          targetPort: 9000 # The port on the container
      type: ClusterIP
    